### PR TITLE
Update utterances.json

### PR DESCRIPTION
**Pull request by ClaireTurner**
As discussed yesterday I have made a few amendments to the utterances.json. Please review and add any additional utterances - thank you Susan.

### CODE REVIEW

**Comment by ClaireTurner** [comment]
Please review when you have the time @sheltons Thank you!

**Comment by sheltons** [comment]
This change has been updated in our production environment (of which this repository is a mirror). Closing without merging.

**Comment by ClaireTurner** [comment]
Thank you!

**Comment by ClaireTurner** [comment]
We have the updated text in Chatbot now - thank you!

**Pull request closed without merging**
